### ISSUE TITLE
Large charts are shown clipped

### ISSUE THREAD

**Issue by ehansis** [altair-viz/altair_viewer#40]
When a large altair chart is displayed in the browser (large = a fair bit larger than your browser window), it is truncated. 

Minimal example:
```python
import altair as alt
import numpy as np
import pandas as pd

df = pd.DataFrame(dict(x=np.linspace(0, 1, 100), y=np.random.random(100)))
chart = alt.Chart(df, width=5000, height=5000).mark_line().encode(x="x", y="y")
chart.show()
```

When I open this in Firefox or Safari (both on Mac), I see approximately the bottom half and left two thirds of the chart. I cannot scroll to the top-left corner. Zooming out in the browser renders the whole chart (in Firefox), but that's not a usable work-around.

This seems to be caused by the properties of the chart's enclosing `div` (lines 23-26 in `_viewer.py`, version 0.3.0):
```
      position: absolute;
      left: 50%;
      top: 50%;
      transform: translate(-50%, -50%);
```

That's nice for showing a small chart centered, but it seems to break the display of very large charts. Removing that code (or deleting the respective properties in the Firefox dev tools) solves the issue.

~~My suggested solution would be to make this configurable either with a switch `center_chart` that includes or does not include the above CSS, or by adding an option to supply custom CSS for the chart's enclosing `div` and the above CSS being the default. What do you think? I'd be happy to take a shot at fixing this.~~

Actually, it would probably be much nicer to find a bit of CSS that works regardless of the chart size and hard-code that in the template. Who wants to remember that fixing a truncated chart requires fiddling with the template CSS...

(Edited: changed my mind about the suggested solution :) )

**Comment by joelostblom** [comment]
Since Altair 5.3, the functionality of Altair Viewer is now available in Altair via the [vl-convert](https://github.com/vega/vl-convert) package instead. See [the docs on how to use the browser renderer](https://altair-viz.github.io/user_guide/display_frontends.html#browser-renderer) to display charts via `.show()`, and the PR https://github.com/altair-viz/altair/pull/3379 for more details.

We are going to archive this repo, so I'm closing all the open issues and PRs before doing so. Try out the new options for rendering charts mentioned above and if you run into issues, please open an issue directly in the altair or vl-convert repo.
