### ISSUE TITLE
Version 0.4.0 does not include updated listing.json

### ISSUE THREAD

**Issue by tempdata73** [altair-viz/altair_viewer#50]
Newest version 0.4.0 does not include vega-lite version 5.2.0 in its `listing.json` file.

This has a cascading effect and generates an error when trying to build documentation on the [altair repo](https://github.com/altair-viz/altair) (I actually discovered this whilst addressing [#2645](https://github.com/altair-viz/altair/issues/2645#issue-1292392205)).

## Reproducing the error
Just run `make html` under the doc directory, having all requirements installed via pip.

Error message:
`
exception: No matches for version='5.2.0' among ['4.0.2', '4.8.1', '4.17.0'].
`
`
Often this can be fixed by updating altair_viewer:
    pip install -U altair_viewer
`

This, however, does not fix the problem.

## Possible solution
Taking a look at the logs, `altair_viewer`'s latest version was published on November 2021, while the `listing.json` file was updated on January 2022. If I'm not terribly mistaken, republishing the package would fix this problem.

**Comment by RomeshA** [comment]
It would be great to have an update for this because the base `altair` package has now been updated on PyPI to expect v5.8, so it's no longer possible to view plots locally since the update to include `vega-lite-5.8.0.js` hasn't been deployed yet

**Comment by franzhaas** [comment]
I believe this is related to this one.:

https://github.com/altair-viz/altair_viewer/issues/52

**Comment by joelostblom** [comment]
Since Altair 5.3, the functionality of Altair Viewer is now available in Altair via the [vl-convert](https://github.com/vega/vl-convert) package instead. See [the docs on how to use the browser renderer](https://altair-viz.github.io/user_guide/display_frontends.html#browser-renderer) to display charts via `.show()`, and the PR https://github.com/altair-viz/altair/pull/3379 for more details.

We are going to archive this repo, so I'm closing all the open issues and PRs before doing so. Try out the new options for rendering charts mentioned above and if you run into issues, please open an issue directly in the altair or vl-convert repo.
