### ISSUE TITLE
Auto-reloading file

### ISSUE THREAD

**Issue by davidgilbertson** [altair-viz/altair_viewer#53]
This is not really an issue, just sharing something that might be useful to others. I found this one of the tricker barriers to using Altair in a way that worked for me. If this is a common enough use case maybe it could be added to the package.

My use case:
* I'm using Altair with PyCharm's Python Console (not Jupyter)
* I want to be able to show charts in a browser window, and have them update when I re-execute my code with changes made.
* A solution that blocks the console doesn't work for me, so I just want to serve the charts with a static server
* I want to be able to have multiple charts open in different tabs.

For this, I create the chart HTML with `chart.to_html()` then inject a script to reload the file when it's updated:
```py
html = chart.to_html().replace(
    "</body>",
    """<script type='text/javascript'>
    const POLL_INTERVAL = 1000
    
    const fetchLastModified = () => fetch(document.location, {method: 'HEAD'})
        .then(res => res.headers.get('last-modified'))
    
    fetchLastModified().then(lastModified => {
      setInterval(() => {
        if (document.hidden) return
    
        fetchLastModified().then(lastModified2 => {
          if (lastModified !== lastModified2) document.location.reload()
        })
      }, POLL_INTERVAL)
    })
    </script>
    </body>
    """,
)
```
The script checks every second for a new version of the file. It only does this while the browser window is visible, and makes a `HEAD` request which is tiny (even so, probably not suitable for anything but local serving).

Then I save this to disk with the chart name and print a link to open it (once per session).

I serve the file with a static web server (PyCharm has http://localhost:63342 always running, others could use `py -m http.server`).

**Comment by joelostblom** [comment]
Since Altair 5.3, the functionality of Altair Viewer is now available in Altair via the [vl-convert](https://github.com/vega/vl-convert) package instead. See [the docs on how to use the browser renderer](https://altair-viz.github.io/user_guide/display_frontends.html#browser-renderer) to display charts via `.show()`, and the PR https://github.com/altair-viz/altair/pull/3379 for more details.

We are going to archive this repo, so I'm closing all the open issues and PRs before doing so. Try out the new options for rendering charts mentioned above and if you run into issues, please open an issue directly in the altair or vl-convert repo.
