### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by jeremyNG-lab** [altair-viz/altair_viewer#58]
line1 = alt.Chart(Data).mark_line().encode(
    x='mean(Value)',
    y='Profondeur',
    color='Type')
line1
Traceback (most recent call last):

  File C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\formatters.py:974 in __call__
    return method(include=include, exclude=exclude)

  File C:\ProgramData\Anaconda3\lib\site-packages\altair\vegalite\v5\api.py:2161 in _repr_mimebundle_
    return renderers.get()(dct)

  File C:\ProgramData\Anaconda3\lib\site-packages\altair_viewer\_viewer.py:323 in render
    out = self.display(

  File C:\ProgramData\Anaconda3\lib\site-packages\altair_viewer\_viewer.py:268 in display
    raise RuntimeError("Internal: _stream is not defined.")

RuntimeError: Internal: _stream is not defined.

**Comment by joelostblom** [comment]
Since Altair 5.3, the functionality of Altair Viewer is now available in Altair via the [vl-convert](https://github.com/vega/vl-convert) package instead. See [the docs on how to use the browser renderer](https://altair-viz.github.io/user_guide/display_frontends.html#browser-renderer) to display charts via `.show()`, and the PR https://github.com/altair-viz/altair/pull/3379 for more details.

We are going to archive this repo, so I'm closing all the open issues and PRs before doing so. Try out the new options for rendering charts mentioned above and if you run into issues, please open an issue directly in the altair or vl-convert repo.
