### ISSUE TITLE
Please support altair version >= 5

### ISSUE THREAD

**Issue by fhg-isi** [altair-viz/altair_viewer#60]

**Comment by joelostblom** [comment]
Could you elaborate on what functionality from altair-viewer you would like to use? Some of its saving-related functionality have been incorporated in altair recently,  e.g. in https://github.com/altair-viz/altair/pull/3251

**Comment by fhg-isi** [comment]
Here
https://altair-viz.github.io/user_guide/display_frontends.html#altair-viewer
it says
"altair_viewer does not yet support Altair 5."

However, it does seem to work after updating great-expectations:

`great-expectations 0.17.14 requires altair<5.0.0,>=4.2.1, but you have altair 5.1.2`

=> Maybe the coment in the altair documentation is outdated.

**Comment by fhg-isi** [comment]
The latest version of altair that is supported by altair_viewer seems to be 4.2.2.
However, altair_viewer does not include an explict version number in its requirements.txt. 
The version "4.17.0" mentioned in the error message does not seem to exist.

**Comment by franzhaas** [comment]
> Could you elaborate on what functionality from altair-viewer you would like to use? Some of its saving-related functionality have been incorporated in altair recently, e.g. in [altair-viz/altair#3251](https://github.com/altair-viz/altair/pull/3251)

Hi 

I would love to have the ability to show my altair charts in an browser like it works with altair<5.0.0 and altair_viewer.

Is there an alternative option for this use case?

Thanks in advance,
Franz

**Comment by joelostblom** [comment]
It's unlikely that altair-viewer will see support for altair >=5, but we will hopefully be able to move the most important functionality into altair via other means such as vl-convert as suggested in https://github.com/altair-viz/altair/issues/3330#issuecomment-1943502889

**Comment by joelostblom** [comment]
Since Altair 5.3, the functionality of Altair Viewer is now available in Altair via the [vl-convert](https://github.com/vega/vl-convert) package instead. See [the docs on how to use the browser renderer](https://altair-viz.github.io/user_guide/display_frontends.html#browser-renderer) to display charts via `.show()`, and the PR https://github.com/altair-viz/altair/pull/3379 for more details.

We are going to archive this repo, so I'm closing all the open issues and PRs before doing so. Try out the new options for rendering charts mentioned above and if you run into issues, please open an issue directly in the altair or vl-convert repo.
